# -------------------------------------------------------------------------
# Flavor
# -------------------------------------------------------------------------
[flavor]
dark = "monokai-vibrant"

# -------------------------------------------------------------------------
# Manager
# -------------------------------------------------------------------------
[mgr]
hovered = { bg = "#131421" }

# -------------------------------------------------------------------------
# Filetype
# -------------------------------------------------------------------------
[filetype]
rules = [
    { name = "*/", fg = "#ababab" }
]
