#!/bin/bash
sudo apt update
sudo add-apt-repository universe -y

sudo apt upgrade -y
mkdir -p ~/.local/bin

if ! command -v zsh 2>&1 >/dev/null
then
    sudo apt-get install zsh -y
fi

if [ ! -d ~/.oh-my-zsh ]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

if ! command -v docker 2>&1 >/dev/null
then
    sudo apt-get remove docker docker-engine docker.io containerd runc

    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null

    sudo chmod a+r /etc/apt/keyrings/docker.gpg
    sudo apt-get update

    sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

    sudo usermod -aG docker $USER
    sudo chmod 666 /var/run/docker.sock
fi

if ! command -v xclip 2>&1 >/dev/null
then
    sudo apt install -y xclip
fi

if ! command -v wmctrl 2>&1 >/dev/null
then
    sudo apt install -y wmctrl
fi
if ! command -v xdotool 2>&1 >/dev/null
then
    sudo apt install -y xdotool
fi

if ! command -v ffplay 2>&1 >/dev/null
then
    sudo apt install -y ffmpeg
fi
if ! command -v tmux 2>&1 >/dev/null
then
    sudo apt install -y tmux
fi

if ! command -v wezterm 2>&1 >/dev/null
then
    curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg
    echo 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
    sudo apt update
    sudo apt install -y wezterm
fi

if ! command -v google-chrome 2>&1 >/dev/null
then
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo apt install ./google-chrome-stable_current_amd64.deb -y
fi

if ! command -v bat 2>&1 >/dev/null
then
    sudo apt install -y bat
    mkdir -p ~/.local/bin
    ln -s /usr/bin/batcat ~/.local/bin/bat
fi

if [ ! -f ~/.fonts/GohuFontuni14NerdFont-Regular.ttf ]; then
    mkdir fonts
    cd fonts
    wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Gohu.zip
    unzip "*.zip" "*.ttf" -d ${HOME}/.fonts
    cd /tmp
fi

if ! command -v nvim 2>&1 >/dev/null
then
    cd /tmp
    wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux-x86_64.tar.gz
    tar xzvf nvim-linux-x86_64.tar.gz
    sudo mv nvim-linux-x86_64 /usr/local/bin/nvim
    cd -
    sudo chmod u+x /usr/local/bin/nvim/bin/nvim
    sudo apt install libfuse2 -y
fi

if [ ! -d ~/.tmux/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi


