# -------------------------------------------------------------------------
# Theme
# -------------------------------------------------------------------------
include=~/.config/fuzzel/catppuccin/catppuccin-mocha/sapphire.ini

# -------------------------------------------------------------------------
# Main
# -------------------------------------------------------------------------
[main]

[colors]
border=272822ff
