# -------------------------------------------------------------------------
# Theme
# -------------------------------------------------------------------------
include=~/.config/fuzzel/catppuccin/catppuccin-mocha/sapphire.ini

# -------------------------------------------------------------------------
# Main
# -------------------------------------------------------------------------
[main]
launch-prefix=/home/surgiie/.local/bin/fuzzel-launcher
