#!/bin/bash
# tools i use and need to upgrade frequently/easily$HOME
upgrade() (
  neovim() {
    echo "Updating neovim..."
    version=$(curl -s https://api.github.com/repos/neovim/neovim/releases/latest | jq -r '.tag_name')

    wget https://github.com/neovim/neovim/releases/download/$version/nvim-linux-x86_64.appimage
    sudo chmod u+x nvim-linux-x86_64.appimage
    sudo mv nvim-linux-x86_64.appimage $HOME/.local/bin/nvim

  }

  kubectl() {
    echo "Updating kubectl..."
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

  }

  tilt() {
    echo "Updating tilt..."
    latest=$(curl -s https://api.github.com/repos/tilt-dev/tilt/releases/latest | grep tag_name | cut -d '"' -f 4 | sed 's/^v//')
    wget "https://github.com/tilt-dev/tilt/releases/download/v$latest/tilt.$latest.linux.x86_64.tar.gz" -O /tmp/tilt.$latest.linux.x86_64.tar.gz
    tar xvf /tmp/tilt.$latest.linux.x86_64.tar.gz -C /tmp
    sudo cp /tmp/tilt /usr/local/bin/tilt
  }

  if [ $# -eq 0 ]; then
    sudo apt update
    sudo apt upgrade -y
    sudo apt autoremove -y
    sudo apt autoclean

    exit 0
  fi
  $@
)
