# -------------------------------------------------------------------------
# Wallpapers
# -------------------------------------------------------------------------
wallpaper {
    monitor = eDP-1
    path = ~/.files/background.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.files/background.jpg
    fit_mode = cover
}

# -------------------------------------------------------------------------
# Options
# -------------------------------------------------------------------------
splash = false
