# -------------------------------------------------------------------------
# Monokai Theme
# -------------------------------------------------------------------------
$base        = rgb(272822)
$text        = rgb(F8F8F2)
$surface0    = rgb(3E3D32)
$mauve       = rgb(AE81FF)
$red         = rgb(F92672)
$green       = rgb(A6E22E)
$yellow      = rgb(E6DB74)
$orange      = rgb(FD971F)
$blue        = rgb(66D9EF)
$cyan        = rgb(A1EFE4)

$accent      = $mauve
$accentAlpha = AE81FF
$textAlpha   = F8F8F2
$mauveAlpha  = AE81FF
