# -------------------------------------------------------------------------
# Accent Colors
# -------------------------------------------------------------------------
$rosewater = rgb(f8f8f2)
$rosewaterAlpha = f8f8f2

$flamingo = rgb(fd971f)
$flamingoAlpha = fd971f

$pink = rgb(f92672)
$pinkAlpha = f92672

$mauve = rgb(ae81ff)
$mauveAlpha = ae81ff

$red = rgb(f92672)
$redAlpha = f92672

$maroon = rgb(f92672)
$maroonAlpha = f92672

$peach = rgb(fd971f)
$peachAlpha = fd971f

$yellow = rgb(e6db74)
$yellowAlpha = e6db74

$green = rgb(a6e22e)
$greenAlpha = a6e22e

$teal = rgb(66d9ef)
$tealAlpha = 66d9ef

$sky = rgb(66d9ef)
$skyAlpha = 66d9ef

$sapphire = rgb(66d9ef)
$sapphireAlpha = 66d9ef

$blue = rgb(66d9ef)
$blueAlpha = 66d9ef

$lavender = rgb(ae81ff)
$lavenderAlpha = ae81ff

# -------------------------------------------------------------------------
# Text Colors
# -------------------------------------------------------------------------
$text = rgb(f8f8f2)
$textAlpha = f8f8f2

$subtext1 = rgb(f8f8f2)
$subtext1Alpha = f8f8f2

$subtext0 = rgb(cfcfc2)
$subtext0Alpha = cfcfc2

# -------------------------------------------------------------------------
# Overlay Colors
# -------------------------------------------------------------------------
$overlay2 = rgb(75715e)
$overlay2Alpha = 75715e

$overlay1 = rgb(75715e)
$overlay1Alpha = 75715e

$overlay0 = rgb(75715e)
$overlay0Alpha = 75715e

# -------------------------------------------------------------------------
# Surface Colors
# -------------------------------------------------------------------------
$surface2 = rgb(49483e)
$surface2Alpha = 49483e

$surface1 = rgb(3e3d32)
$surface1Alpha = 3e3d32

$surface0 = rgb(34342a)
$surface0Alpha = 34342a

# -------------------------------------------------------------------------
# Base Colors
# -------------------------------------------------------------------------
$base = rgb(272822)
$baseAlpha = 272822

$mantle = rgb(1e1f1c)
$mantleAlpha = 1e1f1c

$crust = rgb(141410)
$crustAlpha = 141410
