return {
	"esmuellert/codediff.nvim",
	cmd = "CodeDiff",
	config = function()
		vim.keymap.set("n", "<leader>d", "<cmd>CodeDiff<cr>", { desc = "Open Code Diff", remap = true })
	end,
	opts = {
		highlights = {
			line_insert = "DiffAdd",
			line_delete = "DiffDelete",
			char_insert = nil,
			char_delete = nil,
			char_brightness = nil,
			conflict_sign = nil,
			conflict_sign_resolved = nil,
			conflict_sign_accepted = nil,
			conflict_sign_rejected = nil,
		},
		conflict = {
			accept_incoming = "<leader>ct",
			accept_current = "<leader>co",
			accept_both = "<leader>cb",
			discard = "<leader>cx",
			accept_all_incoming = "<leader>cT",
			accept_all_current = "<leader>cO",
			accept_all_both = "<leader>cB",
			discard_all = "<leader>cX",
			next_conflict = "]x",
			prev_conflict = "[x",
			diffget_incoming = "2do",
			diffget_current = "3do",
		},
		diff = {
			layout = "side-by-side",
			disable_inlay_hints = true,
			max_computation_time_ms = 5000,
			ignore_trim_whitespace = false,
			hide_merge_artifacts = false,
			original_position = "left",
			conflict_ours_position = "right",
			conflict_result_position = "bottom",
			conflict_result_height = 30,
			conflict_result_width_ratio = { 1, 1, 1 },
			cycle_next_hunk = true,
			cycle_next_file = true,
			jump_to_first_change = true,
			highlight_priority = 100,
			compute_moves = false,
		},
		explorer = {
			position = "left",
			width = 40,
			height = 15,
			indent_markers = true,
			initial_focus = "explorer",
			icons = {
				folder_closed = "",
				folder_open = "",
			},
			view_mode = "list",
			flatten_dirs = true,
			file_filter = {
				ignore = { ".git/**", ".jj/**" },
			},
			focus_on_select = false,
			visible_groups = {
				staged = true,
				unstaged = true,
				conflicts = true,
			},
		},
		history = {
			position = "bottom",
			width = 40,
			height = 15,
			initial_focus = "history",
			view_mode = "list",
		},
		keymaps = {
			view = {
				quit = "q",
				next_hunk = "]c",
				prev_hunk = "[c",
				next_file = "]f",
				prev_file = "[f",
				diff_get = "do",
				diff_put = "dp",
				open_in_prev_tab = "gf",
				close_on_open_in_prev_tab = false,
				toggle_stage = "-",
				stage_hunk = "<leader>hs",
				unstage_hunk = "<leader>hu",
				discard_hunk = "<leader>hd",
				hunk_textobject = "ih",
				show_help = "g?",
				align_move = "gm",
				toggle_layout = "t",
			},
		},
	},
}
